# Site Settings
title: "Auto-Scale Metrics Documentation"
description: "A comprehensive guide for Auto-Scale Metrics Helm Chart"
url: "https://<your-github-username>.github.io" # Replace with your GitHub username URL
baseurl: "/<repository-name>" # Replace with your repository name

# Theme Configuration
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Build Settings
markdown: kramdown
highlighter: rouge

# Navigation
navigation:
  - title: "Overview"
    url: /
  - title: "Installation"
    url: /installation/
  - title: "Configuration"
    url: /configuration/
  - title: "Use Cases"
    url: /use-cases/
  - title: "Troubleshooting"
    url: /troubleshooting/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
