apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.app.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval | default "15s" }}
    scrape_configs:
      - job_name: '{{ .Values.app.name }}'
        static_configs:
          - targets: ['{{ .Values.app.name }}:{{ .Values.app.port }}']
      {{- if .Values.prometheus.extraScrapeConfigs }}
      {{ .Values.prometheus.extraScrapeConfigs | nindent 6 }}
      {{- end }}
