# Health Check for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus-health
  namespace: {{ .Values.app.namespace }}
  labels:
    app: prometheus
    {{- include "auto-scale-metrics.labels" . | nindent 4 }}
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-health
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
# Health Check for Prometheus Adapter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter-health
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      containers:
      - name: prometheus-adapter
        image: quay.io/prometheus/adapter:v0.9.1
        livenessProbe:
          httpGet:
            path: /metrics
            port: 6443
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: 6443
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
# Health Check for Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-health
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        livenessProbe:
          httpGet:
            path: {{ .Values.app.metricsPath }}
            port: {{ .Values.app.port }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: {{ .Values.app.metricsPath }}
            port: {{ .Values.app.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 3
