apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "auto-scale-metrics.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
        {{- include "auto-scale-metrics.labels" . | nindent 8 }}
    spec:
      containers:
      - name: prometheus-adapter
        image: {{ .Values.prometheusAdapter.image | default "quay.io/prometheus/adapter:v0.9.1" }}
        args:
          - --config.file=/etc/prometheus-adapter/config.yaml
        volumeMounts:
          - name: config
            mountPath: /etc/prometheus-adapter
      volumes:
        - name: config
          configMap:
            name: prometheus-adapter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: {{ .Values.app.namespace }}
data:
  config.yaml: |
    rules:
      - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
        resources:
          overrides:
            namespace: {resource: "namespace"}
            pod: {resource: "pod"}
        name:
          matches: "^(.*)_total"
          as: "${1}"
        metricsQuery: 'sum(rate(<<.Series>>[1m])) by (<<.GroupBy>>)'
